title = "artem"
baseurl = "https://artem.cool"
theme = "hugo-coder"
languageCode = "en-us"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

#pygmentsstyle = "bw"
#pygmentscodefences = true
#pygmentscodefencesguesssyntax = true

[params]
author = "Artem Gordinskiy"
info = "Human, Software Engineer"
description = "The website and blog of Artem Gordinskiy."
keywords = "blog,developer,personal"
header = "Artem"
avatarurl = "images/avatar.jpg"

favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"

footercontent = ""
hideFooter = false
hideCredits = true
hideCopyright = true
since = 2020

enableTwemoji = false

colorScheme = "auto"
hidecolorschemetoggle = false

customCSS = []
customSCSS = []
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 1
url = "https://twitter.com/artemgordinskiy"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 2
url = "https://www.instagram.com/artemgordinskiy"
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 3
url = "https://github.com/artemgordinskiy"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/artemgordinskiy"
[[params.social]]
name = "Goodreads"
icon = "fa fa-book fa-2x"
weight = 5
url = "https://www.goodreads.com/artemgordinskiy"
[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:hey@artem.cool"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "blog/"
[[menu.main]]
name = "About"
weight = 1
url = "about/"
